(* File generated by the BNF Converter (bnfc 2.9.5). *)

type ident = Ident of string
and grammar =
   MkGrammar of def list

and def =
   Rule of label * cat * item list
 | Comment of string
 | Comments of string * string
 | Internal of label * cat * item list
 | Token of ident * reg
 | PosToken of ident * reg
 | Entryp of ident list
 | Separator of minimumSize * cat * string
 | Terminator of minimumSize * cat * string
 | Coercions of ident * int
 | Rules of ident * rHS list
 | Layout of string list
 | LayoutStop of string list
 | LayoutTop

and item =
   Terminal of string
 | NTerminal of cat

and cat =
   ListCat of cat
 | IdCat of ident

and label =
   LabNoP of labelId
 | LabP of labelId * profItem list
 | LabPF of labelId * labelId * profItem list
 | LabF of labelId * labelId

and labelId =
   Id of ident
 | Wild
 | ListE
 | ListCons
 | ListOne

and profItem =
   ProfIt of intList list * int list

and intList =
   Ints of int list

and rHS =
   MkRHS of item list

and minimumSize =
   MNonempty
 | MEmpty

and reg =
   RSeq of reg * reg
 | RAlt of reg * reg
 | RMinus of reg * reg
 | RStar of reg
 | RPlus of reg
 | ROpt of reg
 | REps
 | RChar of char
 | RAlts of string
 | RSeqs of string
 | RDigit
 | RLetter
 | RUpper
 | RLower
 | RAny

